---
# tasks file for asa_noturna
- name: role para Deploy
  hosts: all
  vars:
    - texto: " Quem vive menos é pq morreu cedo"
  tasks:
    - include: prereqDebian.yml
    - include: prereqRedhat.yml
    - include: install_nginx.yml
    - include: deploy.yml


