- name: Parando Httpd - like red hat
  service:
    name: httpd
    state: stopped
  ignore_errors: True
  when: ansible_os_family == "RedHat"

- name: Removendo HTTPD 
  yum:
    name: httpd
    state: absent
  when: ansible_os_family == "RedHat"
