- name: Parar Apache
  service:
    name: apache2
    state: stopped
  when: ansible_os_family == "Debian"

- name: Removendo Apache - like debian
  apt:
    name: apache2*
    state: absent
  when: ansible_os_family == "Debian"

