---
- name: Playbook do Bruce
  hosts: all
  vars:
    username: capuz_vermelho
  tasks:
   - name: vERIFICANDO MEMORIa
     command: free -h

   - name: desinstalando SL
     apt: name=sl state=absent update_cache=yes
     when: ansible_distribution == "Ubuntu"
   - name: Instalando Pacotes - UBUNTU
     apt:
       name: ['cowsay','vim','nginx']
       state: present
       update_cache: yes
     notify: restart
     when: ansible_distribution == "Ubuntu"

   - name: Instalando SL - Centos
     yum:
       name: ['epel-release','cowsay','sl','nginx']
       state: present
     notify: restart
     when: ansible_distribution == "CentOS"

   - name: Garantindo o Path
     lineinfile:
       path: /etc/profile
       create: yes
       line: "export PATH=$PATH:/usr/games"   
       state: present	

   - name: copiando Arquivos]
     copy:
       src: /etc/ansible/robin
       dest: /tmp/dick_grayson


   - name: garantindo Hosts
     lineinfile:
       path: /etc/hosts
       create: yes
       line: "{{ item }}"
       state: present
     with_items:
     - "192.168.99.10 devops.salas4linux.com.br devops"
     - "192.168.99.20 docker.salas4linux.com.br docker"
     - "192.168.99.30 automation.salas4linux.com.br automation"

   - name: Criando Usuario
     user: name={{ username }} shell=/bin/bash create_home=yes

  handlers:
   - name: restart
     service:
       name: nginx
       state: restarted


  
