---
- name: Stark Playbook
  hosts: all
  tasks:
#UBUNTU
   - name: parar o NGINX
     service:
       name: nginx
       state: stopped
     ignore_errors: True
   - name: Removendo Nginx
     apt: name=nginx* state=absent 
     when: ansible_distribution == "Ubuntu"
#PACOTES UBUNTU
   - name: Instalando Pacotes - UBUNTU
     apt: 
       name: ['apache2','libapache2-mod-php7.0','php7.0']
       state: present
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

#CENTOS
   - name: Instalando httpd / php - Centos
     yum: 
       name: ['httpd','php']
       state: present
     notify: httpd
     when: ansible_distribution == "CentOS"
#Ativa Modulo
   - name: Ativando modulo PHP
     command: a2enmod php7.0
     notify: apache
     when: ansible_distribution == "Ubuntu"
#Desisntala nginx centos

   - name: desinstalando Nginx
     yum:
       name: nginx*
       state: absent
     when: ansible_distribution == "CentOS" 
#copia INDEX
   - name: Copiando Index.php
     copy:
       src: /etc/ansible/index.php
       dest: /var/www/html/index.php

#Gerenciamento de Serviços
  handlers:
   - name: httpd
     service:
       name: httpd
       state: restarted

   - name: apache
     service:
       name: apache2
       state: restarted


  
